# Generated by Django 4.2.4 on 2023-08-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_alter_userdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='registration_state',
            field=models.CharField(choices=[('initial', 'Initial registration'), ('admin_requested_modify', 'Admin requested modifications'), ('waiting_for_approval', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='initial', max_length=255),
        ),
    ]
