# Docker configuration for local development.
# You should run this with a rootless Docker installation,
# so the files created inside the container will be owned
# by your user on the host machine.
services:
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=registrationapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - registrationapp-pgdata:/var/lib/postgresql/data/
    restart: always
  registrationapp:
    build: ./registrationapp
    command: python manage.py runserver 0.0.0.0:8000
    # or command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
    volumes:
      - ./registrationapp:/home/app/registrationapp
    # in rootless mode, the root user in the container is the own user in the host system
    # needed for correct file ownership in the mounted volume
    user: root
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - POSTGRES_NAME=registrationapp
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - EMAIL_HOST=maildev
      - EMAIL_PORT=1025
      - ORCID_URL=https://sandbox.orcid.org
      - ORCID_PUBLIC_API_URL=https://pub.sandbox.orcid.org
      - ORCID_REDIRECT_URI=http://127.0.0.1:8000/register-orcid
    env_file:
      # environment variables not suitable for version control are stored in a file
      - secrets/environment.txt
    secrets:
      - POSTGRES_PASSWORD
      - REGISTRATIONAPP_DJANGO_SECRET_KEY
      - REGISTRATIONAPP_ORCID_CLIENT_SECRET
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: always
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
    restart: always
secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/postgres_password.txt
  REGISTRATIONAPP_DJANGO_SECRET_KEY:
    file: ./secrets/registrationapp_django_secret_key.txt
  REGISTRATIONAPP_ORCID_CLIENT_SECRET:
    file: ./secrets/registrationapp_orcid_client_secret.txt
volumes:
  registrationapp-pgdata: